<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateLicenciaturasMTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('licenciatura_materia', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('licenciatura_id')->unsigned();
            $table->integer('materia_id')->unsigned();

            $table->foreign('licenciatura_id')->references('id')->on('licenciaturas')->onDelete('cascade');
            $table->foreign('materia_id')->references('id')->on('materias')->onDelete('cascade');
            $table->timestamps();
        });

        DB::table('licenciatura_materia')->insert([

            //Materias de ing en sistemas computacionales 
            ['licenciatura_id' => '4','materia_id' => '1'],
            ['licenciatura_id' => '4','materia_id' => '2'],
            ['licenciatura_id' => '4','materia_id' => '3'],
            ['licenciatura_id' => '4','materia_id' => '4'],
            ['licenciatura_id' => '4','materia_id' => '5'],
            ['licenciatura_id' => '4','materia_id' => '6'],
            ['licenciatura_id' => '4','materia_id' => '7'],
            ['licenciatura_id' => '4','materia_id' => '8'],
            ['licenciatura_id' => '4','materia_id' => '9'],
            ['licenciatura_id' => '4','materia_id' => '10'],
            ['licenciatura_id' => '4','materia_id' => '11'],
            ['licenciatura_id' => '4','materia_id' => '12'],
            ['licenciatura_id' => '4','materia_id' => '13'],
            ['licenciatura_id' => '4','materia_id' => '14'],
            ['licenciatura_id' => '4','materia_id' => '15'],
            ['licenciatura_id' => '4','materia_id' => '16'],
            ['licenciatura_id' => '4','materia_id' => '17'],
            ['licenciatura_id' => '4','materia_id' => '18'],
            ['licenciatura_id' => '4','materia_id' => '19'],
            ['licenciatura_id' => '4','materia_id' => '20'],
            ['licenciatura_id' => '4','materia_id' => '21'],
            ['licenciatura_id' => '4','materia_id' => '22'],
            ['licenciatura_id' => '4','materia_id' => '23'],
            ['licenciatura_id' => '4','materia_id' => '24'],
            ['licenciatura_id' => '4','materia_id' => '25'],
            ['licenciatura_id' => '4','materia_id' => '26'],
            ['licenciatura_id' => '4','materia_id' => '27'],
            ['licenciatura_id' => '4','materia_id' => '28'],
            ['licenciatura_id' => '4','materia_id' => '29'],
            ['licenciatura_id' => '4','materia_id' => '30'],
            ['licenciatura_id' => '4','materia_id' => '31'],
            ['licenciatura_id' => '4','materia_id' => '32'],
            ['licenciatura_id' => '4','materia_id' => '33'],
            ['licenciatura_id' => '4','materia_id' => '34'],
            ['licenciatura_id' => '4','materia_id' => '35'],
            ['licenciatura_id' => '4','materia_id' => '36'],
            ['licenciatura_id' => '4','materia_id' => '37'],
            ['licenciatura_id' => '4','materia_id' => '38'],
            ['licenciatura_id' => '4','materia_id' => '39'],
            ['licenciatura_id' => '4','materia_id' => '40'],
            ['licenciatura_id' => '4','materia_id' => '41'],
            ['licenciatura_id' => '4','materia_id' => '42'],
            ['licenciatura_id' => '4','materia_id' => '43'],
            ['licenciatura_id' => '4','materia_id' => '44'],
            ['licenciatura_id' => '4','materia_id' => '45'],
            ['licenciatura_id' => '4','materia_id' => '46'],
            ['licenciatura_id' => '7','materia_id' => '47'],
            ['licenciatura_id' => '7','materia_id' => '48'],
            ['licenciatura_id' => '7','materia_id' => '49'],
            ['licenciatura_id' => '7','materia_id' => '50'],
            ['licenciatura_id' => '7','materia_id' => '51'],
            ['licenciatura_id' => '7','materia_id' => '52'],
            ['licenciatura_id' => '7','materia_id' => '53'],
            ['licenciatura_id' => '7','materia_id' => '54'],
            ['licenciatura_id' => '7','materia_id' => '55'],
            ['licenciatura_id' => '7','materia_id' => '56'],
            ['licenciatura_id' => '7','materia_id' => '57'],
            ['licenciatura_id' => '7','materia_id' => '58'],
            ['licenciatura_id' => '7','materia_id' => '59'],
            ['licenciatura_id' => '7','materia_id' => '60'],
            ['licenciatura_id' => '7','materia_id' => '61'],
            ['licenciatura_id' => '7','materia_id' => '62'],
            ['licenciatura_id' => '7','materia_id' => '63'],
            ['licenciatura_id' => '7','materia_id' => '64'],
            ['licenciatura_id' => '7','materia_id' => '65'],
            ['licenciatura_id' => '7','materia_id' => '66'],
            ['licenciatura_id' => '7','materia_id' => '67'],
            ['licenciatura_id' => '7','materia_id' => '68'],
            ['licenciatura_id' => '7','materia_id' => '69'],
            ['licenciatura_id' => '7','materia_id' => '70'],
            ['licenciatura_id' => '7','materia_id' => '71'],
            ['licenciatura_id' => '7','materia_id' => '72'],
            ['licenciatura_id' => '7','materia_id' => '73'],
            ['licenciatura_id' => '7','materia_id' => '74'],
            ['licenciatura_id' => '7','materia_id' => '75'],
            ['licenciatura_id' => '7','materia_id' => '76'],
            ['licenciatura_id' => '7','materia_id' => '77'],
            ['licenciatura_id' => '7','materia_id' => '78'],
            ['licenciatura_id' => '7','materia_id' => '79'],
            ['licenciatura_id' => '7','materia_id' => '80'],
            ['licenciatura_id' => '7','materia_id' => '81'],
            ['licenciatura_id' => '7','materia_id' => '82'],
            ['licenciatura_id' => '7','materia_id' => '83'],
            ['licenciatura_id' => '7','materia_id' => '84'],     
            ['licenciatura_id' => '5','materia_id' => '85'],
            ['licenciatura_id' => '5','materia_id' => '86'],
            ['licenciatura_id' => '5','materia_id' => '87'],
            ['licenciatura_id' => '5','materia_id' => '88'],
            ['licenciatura_id' => '5','materia_id' => '89'],
            ['licenciatura_id' => '5','materia_id' => '90'],
            ['licenciatura_id' => '5','materia_id' => '91'],
            ['licenciatura_id' => '5','materia_id' => '92'],
            ['licenciatura_id' => '5','materia_id' => '93'],
            ['licenciatura_id' => '5','materia_id' => '94'],
            ['licenciatura_id' => '5','materia_id' => '95'],
            ['licenciatura_id' => '5','materia_id' => '96'],
            ['licenciatura_id' => '5','materia_id' => '97'],
            ['licenciatura_id' => '5','materia_id' => '98'],
            ['licenciatura_id' => '5','materia_id' => '99'],
            ['licenciatura_id' => '5','materia_id' => '100'],
            ['licenciatura_id' => '5','materia_id' => '101'],
            ['licenciatura_id' => '5','materia_id' => '102'],
            ['licenciatura_id' => '5','materia_id' => '103'],
            ['licenciatura_id' => '5','materia_id' => '104'],
            ['licenciatura_id' => '5','materia_id' => '105'],
            ['licenciatura_id' => '5','materia_id' => '106'],
            ['licenciatura_id' => '5','materia_id' => '107'],
            ['licenciatura_id' => '5','materia_id' => '108'],
            ['licenciatura_id' => '5','materia_id' => '109'],
            ['licenciatura_id' => '5','materia_id' => '110'],
            ['licenciatura_id' => '5','materia_id' => '111'],
            ['licenciatura_id' => '5','materia_id' => '112'],
            ['licenciatura_id' => '5','materia_id' => '113'],
            ['licenciatura_id' => '5','materia_id' => '114'],
            ['licenciatura_id' => '5','materia_id' => '115'],
            ['licenciatura_id' => '5','materia_id' => '116'],
            ['licenciatura_id' => '5','materia_id' => '117'],
            ['licenciatura_id' => '5','materia_id' => '118'],
            ['licenciatura_id' => '5','materia_id' => '119'],
            ['licenciatura_id' => '5','materia_id' => '120'],
            ['licenciatura_id' => '5','materia_id' => '121'],       
            ['licenciatura_id' => '6','materia_id' => '122'],
            ['licenciatura_id' => '6','materia_id' => '123'],
            ['licenciatura_id' => '6','materia_id' => '124'],
            ['licenciatura_id' => '6','materia_id' => '125'],
            ['licenciatura_id' => '6','materia_id' => '126'],
            ['licenciatura_id' => '6','materia_id' => '127'],
            ['licenciatura_id' => '6','materia_id' => '128'],
            ['licenciatura_id' => '6','materia_id' => '129'],
            ['licenciatura_id' => '6','materia_id' => '130'],
            ['licenciatura_id' => '6','materia_id' => '131'],
            ['licenciatura_id' => '6','materia_id' => '132'],
            ['licenciatura_id' => '6','materia_id' => '133'],
            ['licenciatura_id' => '6','materia_id' => '134'],
            ['licenciatura_id' => '6','materia_id' => '135'],
            ['licenciatura_id' => '6','materia_id' => '136'],
            ['licenciatura_id' => '6','materia_id' => '137'],
            ['licenciatura_id' => '6','materia_id' => '138'],
            ['licenciatura_id' => '6','materia_id' => '139'],
            ['licenciatura_id' => '6','materia_id' => '140'],
            ['licenciatura_id' => '6','materia_id' => '141'],
            ['licenciatura_id' => '6','materia_id' => '142'],
            ['licenciatura_id' => '6','materia_id' => '143'],
            ['licenciatura_id' => '6','materia_id' => '144'],
            ['licenciatura_id' => '6','materia_id' => '145'],
            ['licenciatura_id' => '6','materia_id' => '146'],
            ['licenciatura_id' => '6','materia_id' => '147'],
            ['licenciatura_id' => '6','materia_id' => '148'],
            ['licenciatura_id' => '6','materia_id' => '149'],
            ['licenciatura_id' => '6','materia_id' => '150'],
            ['licenciatura_id' => '8','materia_id' => '151'],
            ['licenciatura_id' => '8','materia_id' => '152'],
            ['licenciatura_id' => '8','materia_id' => '153'],
            ['licenciatura_id' => '8','materia_id' => '154'],
            ['licenciatura_id' => '8','materia_id' => '155'],
            ['licenciatura_id' => '8','materia_id' => '156'],
            ['licenciatura_id' => '8','materia_id' => '157'],
            ['licenciatura_id' => '8','materia_id' => '158'],
            ['licenciatura_id' => '8','materia_id' => '159'],
            ['licenciatura_id' => '8','materia_id' => '160'],
            ['licenciatura_id' => '8','materia_id' => '161'],
            ['licenciatura_id' => '8','materia_id' => '162'],
            ['licenciatura_id' => '8','materia_id' => '163'],
            ['licenciatura_id' => '8','materia_id' => '164'],
            ['licenciatura_id' => '8','materia_id' => '165'],
            ['licenciatura_id' => '8','materia_id' => '166'],
            ['licenciatura_id' => '8','materia_id' => '167'],
            ['licenciatura_id' => '8','materia_id' => '168'],
            ['licenciatura_id' => '8','materia_id' => '169'],
            ['licenciatura_id' => '8','materia_id' => '170'],
            ['licenciatura_id' => '8','materia_id' => '171'],
            ['licenciatura_id' => '8','materia_id' => '172'],
            ['licenciatura_id' => '8','materia_id' => '173'],
            ['licenciatura_id' => '8','materia_id' => '174'],
            ['licenciatura_id' => '8','materia_id' => '175'],
            ['licenciatura_id' => '8','materia_id' => '176'],
            ['licenciatura_id' => '8','materia_id' => '177'],
            ['licenciatura_id' => '8','materia_id' => '178'],
            ['licenciatura_id' => '8','materia_id' => '179'],
            ['licenciatura_id' => '8','materia_id' => '180'],
            ['licenciatura_id' => '8','materia_id' => '181'],
            ['licenciatura_id' => '8','materia_id' => '182'],
            ['licenciatura_id' => '8','materia_id' => '183'],
            ['licenciatura_id' => '8','materia_id' => '184'],
            ['licenciatura_id' => '8','materia_id' => '185'],
            ['licenciatura_id' => '8','materia_id' => '186'],
            ['licenciatura_id' => '8','materia_id' => '187'],
            ['licenciatura_id' => '8','materia_id' => '188'],
            ['licenciatura_id' => '8','materia_id' => '189'],
            ['licenciatura_id' => '8','materia_id' => '190'],
            ['licenciatura_id' => '8','materia_id' => '191'],
            ['licenciatura_id' => '8','materia_id' => '192'],
            ['licenciatura_id' => '8','materia_id' => '193'],
            ['licenciatura_id' => '8','materia_id' => '194'],
            ['licenciatura_id' => '8','materia_id' => '195'],
            ['licenciatura_id' => '8','materia_id' => '196'],
            ['licenciatura_id' => '8','materia_id' => '197'],
            ['licenciatura_id' => '8','materia_id' => '198'],
            ['licenciatura_id' => '8','materia_id' => '199'],
            ['licenciatura_id' => '8','materia_id' => '200'],
            ['licenciatura_id' => '8','materia_id' => '201'],
            ['licenciatura_id' => '8','materia_id' => '202'],
            ['licenciatura_id' => '1','materia_id' => '203'],
            ['licenciatura_id' => '1','materia_id' => '204'],
            ['licenciatura_id' => '1','materia_id' => '205'],
            ['licenciatura_id' => '1','materia_id' => '206'],
            ['licenciatura_id' => '1','materia_id' => '207'],
            ['licenciatura_id' => '1','materia_id' => '208'],
            ['licenciatura_id' => '1','materia_id' => '209'],
            ['licenciatura_id' => '1','materia_id' => '210'],
            ['licenciatura_id' => '1','materia_id' => '211'],
            ['licenciatura_id' => '1','materia_id' => '212'],
            ['licenciatura_id' => '1','materia_id' => '213'],
            ['licenciatura_id' => '1','materia_id' => '214'],
            ['licenciatura_id' => '1','materia_id' => '215'],
            ['licenciatura_id' => '1','materia_id' => '216'],
            ['licenciatura_id' => '1','materia_id' => '217'],
            ['licenciatura_id' => '1','materia_id' => '218'],
            ['licenciatura_id' => '1','materia_id' => '219'],
            ['licenciatura_id' => '1','materia_id' => '220'],
            ['licenciatura_id' => '1','materia_id' => '221'],
            ['licenciatura_id' => '1','materia_id' => '222'],
            ['licenciatura_id' => '1','materia_id' => '223'],
            ['licenciatura_id' => '1','materia_id' => '224'],
            ['licenciatura_id' => '1','materia_id' => '225'],
            ['licenciatura_id' => '1','materia_id' => '226'],
            ['licenciatura_id' => '1','materia_id' => '227'],
            ['licenciatura_id' => '1','materia_id' => '228'],
            ['licenciatura_id' => '1','materia_id' => '229'],
            ['licenciatura_id' => '1','materia_id' => '230'],
            ['licenciatura_id' => '1','materia_id' => '231'],
            ['licenciatura_id' => '1','materia_id' => '232'],
            ['licenciatura_id' => '1','materia_id' => '233'],
            ['licenciatura_id' => '1','materia_id' => '234'],
            ['licenciatura_id' => '1','materia_id' => '235'],
            ['licenciatura_id' => '1','materia_id' => '236'],
            ['licenciatura_id' => '1','materia_id' => '237'],
            ['licenciatura_id' => '1','materia_id' => '238'],
            ['licenciatura_id' => '1','materia_id' => '239'],
            ['licenciatura_id' => '1','materia_id' => '240'],
            ['licenciatura_id' => '1','materia_id' => '241'],
            ['licenciatura_id' => '1','materia_id' => '242'],
            ['licenciatura_id' => '1','materia_id' => '243'],
            ['licenciatura_id' => '1','materia_id' => '244'],
            ['licenciatura_id' => '1','materia_id' => '245'],
            ['licenciatura_id' => '1','materia_id' => '246'],
            ['licenciatura_id' => '1','materia_id' => '247'],
            ['licenciatura_id' => '1','materia_id' => '248'],
            ['licenciatura_id' => '1','materia_id' => '249'],
            ['licenciatura_id' => '1','materia_id' => '250'],
            ['licenciatura_id' => '1','materia_id' => '251'],
            ['licenciatura_id' => '1','materia_id' => '252'],
            ['licenciatura_id' => '1','materia_id' => '253'],
            ['licenciatura_id' => '1','materia_id' => '254'],
            ['licenciatura_id' => '1','materia_id' => '255'],
            ['licenciatura_id' => '1','materia_id' => '256'],
            ['licenciatura_id' => '2','materia_id' => '257'],
            ['licenciatura_id' => '2','materia_id' => '258'],
            ['licenciatura_id' => '2','materia_id' => '259'],
            ['licenciatura_id' => '2','materia_id' => '260'],
            ['licenciatura_id' => '2','materia_id' => '261'],
            ['licenciatura_id' => '2','materia_id' => '262'],
            ['licenciatura_id' => '2','materia_id' => '263'],
            ['licenciatura_id' => '2','materia_id' => '264'],
            ['licenciatura_id' => '2','materia_id' => '265'],
            ['licenciatura_id' => '2','materia_id' => '266'],
            ['licenciatura_id' => '2','materia_id' => '267'],
            ['licenciatura_id' => '2','materia_id' => '268'],
            ['licenciatura_id' => '2','materia_id' => '269'],
            ['licenciatura_id' => '2','materia_id' => '270'],
            ['licenciatura_id' => '2','materia_id' => '271'],
            ['licenciatura_id' => '2','materia_id' => '272'],
            ['licenciatura_id' => '2','materia_id' => '273'],
            ['licenciatura_id' => '2','materia_id' => '274'],
            ['licenciatura_id' => '2','materia_id' => '275'],
            ['licenciatura_id' => '2','materia_id' => '276'],
            ['licenciatura_id' => '2','materia_id' => '277'],
            ['licenciatura_id' => '2','materia_id' => '278'],
            ['licenciatura_id' => '2','materia_id' => '279'],
            ['licenciatura_id' => '2','materia_id' => '280'],
            ['licenciatura_id' => '2','materia_id' => '281'],
            ['licenciatura_id' => '2','materia_id' => '282'],
            ['licenciatura_id' => '2','materia_id' => '283'],
            ['licenciatura_id' => '2','materia_id' => '284'],
            ['licenciatura_id' => '2','materia_id' => '285'],
            ['licenciatura_id' => '2','materia_id' => '286'],
            ['licenciatura_id' => '2','materia_id' => '287'],
            ['licenciatura_id' => '2','materia_id' => '288'],
            ['licenciatura_id' => '2','materia_id' => '289'],
            ['licenciatura_id' => '2','materia_id' => '290'],
            ['licenciatura_id' => '2','materia_id' => '291'],
            ['licenciatura_id' => '2','materia_id' => '292'],
            ['licenciatura_id' => '2','materia_id' => '293'],
            ['licenciatura_id' => '2','materia_id' => '294'],
            ['licenciatura_id' => '2','materia_id' => '295'],
            ['licenciatura_id' => '2','materia_id' => '296'],
            ['licenciatura_id' => '2','materia_id' => '297'],
            ['licenciatura_id' => '2','materia_id' => '298'],
            ['licenciatura_id' => '2','materia_id' => '299'],
            ['licenciatura_id' => '2','materia_id' => '300'],
            ['licenciatura_id' => '2','materia_id' => '301'],
            ['licenciatura_id' => '2','materia_id' => '302'],
            ['licenciatura_id' => '2','materia_id' => '303'],
            ['licenciatura_id' => '2','materia_id' => '304'],
            ['licenciatura_id' => '2','materia_id' => '305'],
            ['licenciatura_id' => '2','materia_id' => '306'],
            ['licenciatura_id' => '2','materia_id' => '307'],
            ['licenciatura_id' => '2','materia_id' => '308'],
            ['licenciatura_id' => '2','materia_id' => '309'],
            ['licenciatura_id' => '3','materia_id' => '310'],
            ['licenciatura_id' => '3','materia_id' => '311'],
            ['licenciatura_id' => '3','materia_id' => '312'],
            ['licenciatura_id' => '3','materia_id' => '313'],
            ['licenciatura_id' => '3','materia_id' => '314'],
            ['licenciatura_id' => '3','materia_id' => '315'],
            ['licenciatura_id' => '3','materia_id' => '316'],
            ['licenciatura_id' => '3','materia_id' => '317'],
            ['licenciatura_id' => '3','materia_id' => '318'],
            ['licenciatura_id' => '3','materia_id' => '319'],
            ['licenciatura_id' => '3','materia_id' => '320'],
            ['licenciatura_id' => '3','materia_id' => '321'],
            ['licenciatura_id' => '3','materia_id' => '322'],
            ['licenciatura_id' => '3','materia_id' => '323'],
            ['licenciatura_id' => '3','materia_id' => '324'],
            ['licenciatura_id' => '3','materia_id' => '325'],
            ['licenciatura_id' => '3','materia_id' => '326'],
            ['licenciatura_id' => '3','materia_id' => '327'],
            ['licenciatura_id' => '3','materia_id' => '328'],
            ['licenciatura_id' => '3','materia_id' => '329'],
            ['licenciatura_id' => '3','materia_id' => '330'],
            ['licenciatura_id' => '3','materia_id' => '331'],
            ['licenciatura_id' => '3','materia_id' => '332'],
            ['licenciatura_id' => '3','materia_id' => '333'],
            ['licenciatura_id' => '3','materia_id' => '334'],
            ['licenciatura_id' => '3','materia_id' => '335'],
            ['licenciatura_id' => '3','materia_id' => '336'],
            ['licenciatura_id' => '3','materia_id' => '337'],
            ['licenciatura_id' => '3','materia_id' => '338'],
            ['licenciatura_id' => '3','materia_id' => '339'],
            ['licenciatura_id' => '3','materia_id' => '340'],
            ['licenciatura_id' => '3','materia_id' => '341'],
            ['licenciatura_id' => '3','materia_id' => '342'],
            ['licenciatura_id' => '3','materia_id' => '343'],
            ['licenciatura_id' => '3','materia_id' => '344'],
            ['licenciatura_id' => '3','materia_id' => '345'],
            ['licenciatura_id' => '3','materia_id' => '346'],
            ['licenciatura_id' => '3','materia_id' => '347'],
            ['licenciatura_id' => '3','materia_id' => '348'],
            ['licenciatura_id' => '3','materia_id' => '349'],
            ['licenciatura_id' => '3','materia_id' => '350'],
            ['licenciatura_id' => '3','materia_id' => '351'],
            ['licenciatura_id' => '3','materia_id' => '352'],
            ['licenciatura_id' => '3','materia_id' => '353'],
            ['licenciatura_id' => '3','materia_id' => '354'],
            ['licenciatura_id' => '3','materia_id' => '355'],
            ['licenciatura_id' => '3','materia_id' => '356'],
            ['licenciatura_id' => '3','materia_id' => '357'],


        // Fin de las materias de la licenciatura ingenieria en sistemas computacionales
        ]);    
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('licenciaturas_materias');
    }
}
